
# From the host and outside of kubernetes cluster
#curl -I http://192.168.125.128:30007
#curl -I http://192.168.125.129:30007
#curl -I http://192.168.125.130:30007

# From inside any of the Pod of the cluster
# curl -I http://my-node-service:8005

apiVersion: v1
kind: Service
metadata:
  name: my-node-service
spec:
  type: NodePort
  selector:
    app: nginx-test
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8085
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
